# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: # compilation and test
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # this will test the
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4 # get the code to be tested from GitHub
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4 # install Node.js
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci # install dependencies (faster than npm install)
    - run: npm run build --if-present
    - run: npm test
